language: node_js
node_js: - '7'
deploy:
  provider: npm
  email: jacklam718@gmail.com
  api_key:
    secure: lufwz6mX0VkTWGgKwn1fsMpc/ZAul7M8bY5mjlrAGQX9mBpOinxSPPNBTVIqAUYVkO8yn3RQO+PT88Qf99t7dZWoNavY8rKtQVv35IuupV67zdEYOfxG7RVsVXfF/7Elr4+VgEFTs7amoYYjtPLCHEQ5o2niLx9cRtiFMlPvphYP6mGuUAtdrlwVzyZzrl1KfhpoWwsHw2f3y6aCN6y/AG2emRQoMPV28haYlbTzL9C/NyBqHbKuBa/v0wMKVmwrkbUDwdZ7AymiTCEpRdnPOTqfNcnQFJtsdpqzr7IKsByqvNOFA6KlYvivTF6IFiqdk5UZJP+t3e9uQOYLoRdvQkHqupuTpbB2lt8mzKc9VDAeOXnNyD+coz7tWqUkKnGeXqJIEloMdbQt33OAw/ba35waaMRCK6CBXpTzoUdhljJKcEkctOiICEZ5F1sc5/5pp8+nwhEzDsy3CVRrJbUNS6c5z4dAJqMc1dIhCrJQETXuG+PZJxlr84GhNo7VQ6yiZ9acRaQvYtanmC3q4pc6snFNLQKYoJtJwKQigGLgM53EF2QuRjHTN3SfFdl+y5g10EDme0FOA96AC64SrcbtYy+Om4oYncRraZ7m+4qlZvdVqFyddNnVLDy911GKsCE4McQl58uOmSB4l7ge+U5ut3Fo211ooWoyW0XWEMcT0E4=
  on:
    tags: true
    repo: jacklam718/react-native-popup-dialog
